### ISSUE TITLE
v1.0 Checklist

### ISSUE THREAD

**Issue by le717** [le717/linescan.py#1]
- [x] Option to return exception details
- [x] API documentation in `README.md`
- [x] Finish example usage
- [ ] [http://www.gpg4win.org/](http://www.gpg4win.org/)
- [ ] Upload to PyPI ([http://docs.python.org/3/distutils/packageindex.html](http://docs.python.org/3/distutils/packageindex.html))
